name: Deploy Result to Amazon ECS

on:
  push:
    branches:
      - main
    paths:
      - 'result/**'
      - '.github/workflows/deploy-result.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-result:
    name: Build and Deploy result Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::027155467263:role/liya-GitHubActionsDeployToECS
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_URI=027155467263.dkr.ecr.us-east-1.amazonaws.com/liya-result-app:latest
          docker build -t $IMAGE_URI result
          docker push $IMAGE_URI

      - name: Force new deployment on ECS
        run: |
          aws ecs update-service \
            --cluster liya-voting-app-cluster \
            --service liya-result-service \
            --force-new-deployment
